/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.server.productionserver.api;

import com.server.productionserver.model.Box;
import com.server.productionserver.model.ProductNotice;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-06T17:21:33.341303800+08:00[Asia/Shanghai]")

@Validated
@Api(value = "box", description = "the box API")
public interface BoxApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /reqDelBox : 根据id删除箱信息
     *
     * @param boxId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id删除箱信息", nickname = "boxBoxIdDelete", notes = "", response = Object.class, tags={ "箱表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqDelBox",
            produces = { "application/json" },
            consumes = { "multipart/form-data" },
            method = RequestMethod.DELETE)
    default ResponseEntity<Object> boxBoxIdDelete(@ApiParam(value = "",required=true) @RequestParam("id") String boxId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqGetBox : 根据id获取箱信息
     *
     * @param boxId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id获取箱信息", nickname = "boxBoxIdGet", notes = "", response = Object.class, tags={ "箱表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetBox",
            produces = { "application/json" },
            consumes = { "multipart/form-data" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> boxBoxIdGet(@ApiParam(value = "",required=true) @RequestParam("id") String boxId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /reqSetBox : 根据id修改箱信息
     *
     * @param boxId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id修改箱信息", nickname = "boxBoxIdPut", notes = "", response = Object.class, tags={ "箱表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqSetBox",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PUT)
    default ResponseEntity<Object> boxBoxIdPut(@ApiParam(value = "", required=true) @RequestBody Box box) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /reqGetAllBox : 查询全部箱
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "查询全部箱", nickname = "boxGet", notes = "", response = Object.class, tags={ "箱表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetAllBox",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default ResponseEntity<Object> boxGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqAddBox : 插入箱信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "插入箱信息", nickname = "boxPost", notes = "", response = Object.class, tags={ "箱表", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqAddBox",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> boxPost(@ApiParam(value = "", required=true) @RequestBody Box box) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
