/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.server.productionserver.api;

import com.server.productionserver.model.CurlDirection;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-06T17:21:33.341303800+08:00[Asia/Shanghai]")

@Validated
@Api(value = "curl_direction", description = "the curl_direction API")
public interface CurlDirectionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /reqGetAllCustDire : 获取卷曲描述信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "获取卷曲描述信息", nickname = "curlDirectionGet", notes = "", response = Object.class, tags={ "卷曲描述表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetAllCustDire",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default ResponseEntity<Object> curlDirectionGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqAddCustDire : 新建卷曲描述信息
     *
     * @param dirDescription  (optional)
     * @param cusId  (optional)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "新建卷曲描述信息", nickname = "curlDirectionPost", notes = "", response = Object.class, tags={ "卷曲描述表", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqAddCustDire",
            produces = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> curlDirectionPost(@ApiParam(value = "", required=true) @RequestBody CurlDirection curlreq) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /reqDelCustDire : 删除卷曲描述信息
     *
     * @param cusId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "删除卷曲描述信息", nickname = "curlDirectioncusIdDelete", notes = "", response = Object.class, tags={ "卷曲描述表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqDelCustDire",
            produces = { "application/json" },
            method = RequestMethod.DELETE)
    default ResponseEntity<Object> curlDirectioncusIdDelete(@ApiParam(value = "",required=true) @RequestParam("id") String cusId, @ApiParam(value = "",required=true) @RequestParam("num") String num) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqGetCustDire : 根据客户id获取卷曲描述信息
     *
     * @param cusId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据项目id获取卷曲描述信息", nickname = "curlDirectioncusIdGet", notes = "", response = Object.class, tags={ "卷曲描述表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetCustDire",
            produces = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> curlDirectioncusIdGet(@ApiParam(value = "",required=true) @RequestParam("id") String cusId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /curl_direction/{id} : 修改卷曲描述信息
     *
     * @param cusId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "修改卷曲描述信息", nickname = "curlDirectioncusIdPut", notes = "", response = Object.class, tags={ "卷曲描述表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/curl_direction",
            produces = { "application/json" },
            method = RequestMethod.PUT)
    default ResponseEntity<Object> curlDirectioncusIdPut(@ApiParam(value = "", required=true) @RequestBody CurlDirection curlreq) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
