/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.server.productionserver.api;

import com.server.productionserver.model.PackageRequirements;
import com.server.productionserver.model.Production;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-06T17:21:33.341303800+08:00[Asia/Shanghai]")

@Validated
@Api(value = "package_requirements", description = "the package_requirements API")
public interface PackageRequirementsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /reqGetAllCustPacReq : 获取所有打包要求信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "获取所有打包要求信息", nickname = "packageRequirementsGet", notes = "", response = Object.class, tags={ "打包要求表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetAllCustPacReq",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default ResponseEntity<Object> packageRequirementsGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqAddCustPacReq : 新建打包要求信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "新建打包要求信息", nickname = "packageRequirementsPost", notes = "", response = Object.class, tags={ "打包要求表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqAddCustPacReq",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> packageRequirementsPost(@ApiParam(value = "", required=true) @RequestBody PackageRequirements pacreq) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /reqDelCustPacReq : 根据id删除打包要求信息
     *
     * @param cusId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id删除打包要求信息", nickname = "packageRequirementscusIdDelete", notes = "", response = Object.class, tags={ "打包要求表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqDelCustPacReq",
            produces = { "application/json" },
            method = RequestMethod.DELETE)
    default ResponseEntity<Object> packageRequirementscusIdDelete(@ApiParam(value = "",required=true) @RequestParam("id") String cusId, @ApiParam(value = "",required=true) @RequestParam("num") String num) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqGetCustPacReq: 根据项目id获取打包要求
     *
     * @param cusId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据项目id获取打包要求", nickname = "packageRequirementscusIdGet", notes = "", response = Object.class, tags={ "打包要求表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetCustPacReq",
            produces = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> packageRequirementscusIdGet(@ApiParam(value = "",required=true) @RequestParam("id") String cusId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /reqSetCustPacReq : 修改打包要求信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "修改打包要求信息", nickname = "packageRequirementsPut", notes = "", response = Object.class, tags={ "打包要求表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqSetCustPacReq",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PUT)
    default ResponseEntity<Object> packageRequirementsPut(@ApiParam(value = "", required=true) @RequestBody PackageRequirements pacreq) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
