/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.server.productionserver.api;

import com.server.productionserver.model.ProductNotice;
import com.server.productionserver.model.Production;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-09T17:21:33.341303800+08:00[Asia/Shanghai]")

@Validated
@Api(value = "production", description = "the production API")
public interface ProductionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /reqDelProduct : 根据id删除产品信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id删除产品信息", nickname = "producitonIdDelete", notes = "", response = Object.class, tags={ "产品表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class),
            @ApiResponse(code = 404, message = "找不到记录", response = Object.class)})
    @RequestMapping(value = "/reqDelProduct",
            produces = { "application/json" },
            consumes = { "multipart/form-data" },
            method = RequestMethod.DELETE)
    default ResponseEntity<Object> productionIdDelete(@ApiParam(value = "", required=true) @RequestParam(value="id", required=true)  String productionId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqGetProduct : 根据id获取产品信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id获取产品信息", nickname = "productionIdGet", notes = "", response = Object.class, tags={ "产品表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetProduct",
            produces = { "application/json" },
            consumes = { "multipart/form-data" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> productionIdGet(@ApiParam(value = "", required=true) @RequestParam(value="id", required=true)  String productionId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /reqSetProduct : 修改产品信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id修改产品信息", nickname = "productionPut", notes = "", response = Object.class, tags={ "产品表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class),
            @ApiResponse(code = 404, message = "记录不存在", response = Object.class)})
    @RequestMapping(value = "/reqSetProduct",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PUT)
    default ResponseEntity<Object> productionPut(@ApiParam(value = "", required=true) @RequestBody Production production) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /reqGetAllProduct : 查询全部产品
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "查询全部产品", nickname = "productionGet", notes = "", response = Object.class, tags={ "产品表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetAllProduct",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default ResponseEntity<Object> boxGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqAddProduct: 插入产品信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "插入产品信息", nickname = "productionPost", notes = "", response = Object.class, tags={ "产品表", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "成功", response = Object.class),
            @ApiResponse(code = 403, message = "禁止访问", response = Object.class)
    })
    @RequestMapping(value = "/reqAddProduct",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> productionPost(@ApiParam(value = "", required=true) @RequestBody Production production) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
