/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.server.productionserver.api;

import com.server.productionserver.model.Staff;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-06T17:21:33.341303800+08:00[Asia/Shanghai]")

@Validated
@Api(value = "staff", description = "the staff API")
public interface StaffApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /reqGetAllStaff : 查询全部员工信息
     *
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "查询全部员工信息", nickname = "staffGet", notes = "", response = Object.class, tags={ "员工表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetAllStaff",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default ResponseEntity<Object> staffGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqAddStaff : 插入员工信息
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "插入员工信息", nickname = "staffPost", notes = "", response = Object.class, tags={ "员工表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqAddStaff",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> staffPost(@ApiParam(value = "", required=true) @RequestBody Staff staff) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /reqDelStaff : 根据id删除员工信息
     *
     * @param staffId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id删除员工信息", nickname = "staffStaffIdDelete", notes = "", response = Object.class, tags={ "员工表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqDelStaff",
            produces = { "application/json" },
            method = RequestMethod.DELETE)
    default ResponseEntity<Object> staffStaffIdDelete(@ApiParam(value = "",required=true) @RequestParam("id") String id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /reqGetStaff : 根据id获取员工信息
     *
     * @param staffId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id获取员工信息", nickname = "staffStaffIdGet", notes = "", response = Object.class, tags={ "员工表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqGetStaff",
            produces = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<Object> staffStaffIdGet(@ApiParam(value = "") @RequestParam("id") String id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /reqSetStaff: 根据id修改员工信息
     *
     * @param staffId  (required)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "根据id修改员工信息", nickname = "staffStaffIdPut", notes = "", response = Object.class, tags={ "员工表", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class) })
    @RequestMapping(value = "/reqSetStaff",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PUT)
    default ResponseEntity<Object> staffStaffIdPut(@ApiParam(value = "", required=true) @RequestBody Staff staff) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
